from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = REPO_ROOT / "back"
sys.path.insert(0, str(BACKEND_ROOT))

from sqlalchemy import text

from app.agent_zp.service import AgentZpError, import_agent_zp_candidate
from app.core.config import settings
from app.core.db import SessionLocal
from app.import_types import ImportType
from app.import_uploads import service as upload_service
from app.import_uploads.errors import UploadError
from app.schemas.agent_zp import AgentZpImportCreateIn
from app.services import import_jobs
from app.services.import_planner import plan_zip_ingest
from app.services.import_selection import validate_import_selection
from app.zp_conversion.repository import ensure_zp_conversion_schema


MIN_FREE_BYTES = 10 * 1024**3
POLL_INTERVAL_SECONDS = 5


@dataclass(frozen=True)
class Case:
    import_type: str
    source_dir: Path
    method: str
    verify_profile: str
    timeout_seconds: int


def _all_cases(root: Path) -> list[Case]:
    return [
        Case("TD_TOPPIC_HTML", root / "TD_TOPPIC_HTML", "path-import", "top_down", 7200),
        Case("TD_PRSM_BUNDLE", root / "TD_PRSM_BUNDLE", "managed-upload", "top_down", 2400),
        Case("TD_TOPPIC_NATIVE", root / "TD_TOPPIC_NATIVE", "managed-upload", "top_down", 2400),
        Case("BU_DIA_NN", root / "BU_DIA_NN", "managed-upload", "bottom_up", 7200),
        Case("BU_DIA_CLIP", root / "BU_DIA_CLIP", "managed-upload", "bottom_up", 7200),
        Case("TD_MZML", root / "TD_MZML", "managed-upload", "spectra", 2400),
        Case("TD_RAW", root / "TD_RAW", "managed-upload", "spectra", 2400),
        Case("DDA_RAW", root / "DDA_RAW", "managed-upload", "spectra", 2400),
    ]


def _slug(run_label: str, import_type: str) -> str:
    return f"support_{run_label}_{import_type.lower()}"


def _iter_files(root: Path) -> list[Path]:
    return sorted((path for path in root.rglob("*") if path.is_file()), key=lambda path: path.relative_to(root).as_posix())


def _tree_size(paths: Iterable[Path]) -> int:
    total = 0
    for path in paths:
        try:
            total += path.stat().st_size
        except OSError:
            continue
    return total


def _free_bytes() -> int:
    return shutil.disk_usage(settings.resolved_data_root).free


def _gb(value: int | float) -> float:
    return round(float(value) / 1024**3, 3)


def _check_space(label: str) -> None:
    free = _free_bytes()
    print(f"[space] {label}: free={_gb(free)}GB", flush=True)
    if free < MIN_FREE_BYTES:
        raise RuntimeError(f"LOW_SPACE: E drive free space is below 10GB after {label}")


async def _file_chunks(path: Path):
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(settings.import_upload_chunk_bytes)
            if not chunk:
                break
            yield chunk


async def _upload_tree(case: Case) -> str:
    import_type = ImportType(case.import_type)
    files = _iter_files(case.source_dir)
    if not files:
        raise RuntimeError("source directory has no files")
    if len(files) > settings.import_upload_max_files:
        raise RuntimeError(
            f"upload file count {len(files)} exceeds limit {settings.import_upload_max_files}"
        )
    total_size = _tree_size(files)
    print(
        f"[upload] {case.import_type}: files={len(files)} size={_gb(total_size)}GB",
        flush=True,
    )
    if _free_bytes() - total_size < MIN_FREE_BYTES:
        raise RuntimeError(f"LOW_SPACE: uploading {case.import_type} would leave less than 10GB")

    created = upload_service.create_upload(import_type)
    for index, path in enumerate(files, start=1):
        rel = path.relative_to(case.source_dir).as_posix()
        size = path.stat().st_size
        await upload_service.upload_file(
            upload_id=created.upload_id,
            relative_path=rel,
            content_length_header=str(size),
            chunks=_file_chunks(path),
        )
        if index == len(files) or index % 100 == 0:
            print(f"[upload] {case.import_type}: {index}/{len(files)} files", flush=True)

    started = upload_service.start_upload(
        created.upload_id,
        parameters={
            "slug": _slug(RUN_LABEL, case.import_type),
            "name": f"Support Acceptance {case.import_type}",
            "description": "Generated by cs/支持格式上传验收.py",
        },
    )
    return started.job_id


def _path_import(case: Case) -> str:
    plan = plan_zip_ingest(case.source_dir)
    validate_import_selection(ImportType(case.import_type), case.source_dir, plan)
    job = import_jobs.enqueue_path_import(
        source_path=str(case.source_dir),
        slug=_slug(RUN_LABEL, case.import_type),
        name=f"Support Acceptance {case.import_type}",
        description="Generated by cs/支持格式上传验收.py",
        import_type=case.import_type,
    )
    return job.job_id


def _wait_job(job_id: str, *, timeout_seconds: int) -> dict[str, Any]:
    deadline = time.monotonic() + timeout_seconds
    last_status = None
    while True:
        job = import_jobs.get_job(job_id)
        if job is None:
            raise RuntimeError(f"import job disappeared: {job_id}")
        marker = (job.status, job.stage, round(float(job.progress or 0), 1), job.stage_detail)
        if marker != last_status:
            print(
                f"[job] {job_id} status={job.status} stage={job.stage} "
                f"progress={job.progress:.1f} detail={job.stage_detail}",
                flush=True,
            )
            last_status = marker
        if job.status in {"success", "failed"}:
            return {
                "job_id": job.job_id,
                "status": job.status,
                "message": job.message,
                "error": job.error,
                "progress": job.progress,
                "stage": job.stage,
                "stage_detail": job.stage_detail,
            }
        if time.monotonic() > deadline:
            raise RuntimeError(f"import job timed out after {timeout_seconds}s: {job_id}")
        time.sleep(POLL_INTERVAL_SECONDS)


def _dataset_row(slug: str) -> dict[str, Any] | None:
    with SessionLocal() as session:
        row = session.execute(
            text(
                """
                SELECT dataset_id, slug, dataset_name, analysis_mode, source_software,
                       source_root, status, capabilities, extra_metadata
                FROM datasets
                WHERE slug = :slug
                """
            ),
            {"slug": slug},
        ).mappings().one_or_none()
        return dict(row) if row else None


def _latest_support_dataset(import_type: str) -> dict[str, Any] | None:
    suffix = "agent_zp" if import_type == "AGENT_ZP" else import_type.lower()
    with SessionLocal() as session:
        row = session.execute(
            text(
                """
                SELECT dataset_id, slug, dataset_name, analysis_mode, source_software,
                       source_root, status, capabilities, extra_metadata
                FROM datasets
                WHERE source_import_kind = :import_type
                  AND slug LIKE :slug_pattern
                ORDER BY dataset_id DESC
                LIMIT 1
                """
            ),
            {
                "import_type": import_type,
                "slug_pattern": f"support\\_%\\_{suffix}",
            },
        ).mappings().one_or_none()
        return dict(row) if row else None


def _active_zp(dataset_id: int) -> dict[str, Any] | None:
    with SessionLocal() as session:
        row = session.execute(
            text(
                """
                SELECT asset_id, zp_path, format_version, output_sha256, status
                FROM dataset_zp_assets
                WHERE dataset_id = :dataset_id AND status = 'active'
                ORDER BY asset_id DESC
                LIMIT 1
                """
            ),
            {"dataset_id": dataset_id},
        ).mappings().one_or_none()
        return dict(row) if row else None


def _counts(dataset_id: int) -> dict[str, int]:
    with SessionLocal() as session:
        out: dict[str, int] = {}
        for name, sql in {
            "runs": "SELECT count(*) FROM runs WHERE dataset_id = :dataset_id",
            "proteins": "SELECT count(*) FROM proteins WHERE dataset_id = :dataset_id",
            "proteoforms": "SELECT count(*) FROM proteoforms WHERE dataset_id = :dataset_id",
            "peptides": "SELECT count(*) FROM peptides WHERE dataset_id = :dataset_id",
            "matches": "SELECT count(*) FROM identification_matches WHERE dataset_id = :dataset_id",
        }.items():
            out[name] = int(session.scalar(text(sql), {"dataset_id": dataset_id}) or 0)
        return out


def _first_run(dataset_id: int) -> int | None:
    with SessionLocal() as session:
        value = session.scalar(
            text("SELECT run_id FROM runs WHERE dataset_id = :dataset_id ORDER BY run_id LIMIT 1"),
            {"dataset_id": dataset_id},
        )
        return int(value) if value is not None else None


def _first_scan(dataset_id: int, run_id: int) -> int | None:
    from app.services.mzml_scan_index import load_scan_index

    with SessionLocal() as session:
        index = load_scan_index(session, dataset_id, run_id)
        return int(index.scan_number[0]) if index.scan_count else None


def _verify_bottom_up(dataset: dict[str, Any]) -> dict[str, Any]:
    from app.bu.deps import require_bu_dataset, require_bu_match
    from app.bu.services import chromatogram_service, lists_service, overview_service, spectrum_facade, xic_service

    slug = str(dataset["slug"])
    with SessionLocal() as session:
        bu_dataset = require_bu_dataset(session, slug)
        overview = overview_service.get_overview(session, bu_dataset)
        matches = lists_service.list_matches(
            session,
            bu_dataset,
            page=1,
            page_size=1,
            q_max=None,
            run_id=None,
            peptide_id=None,
            protein_id=None,
            charge=None,
            search=None,
            decoy=False,
            sort="q_value",
            order="asc",
        )
        proteins = lists_service.list_proteins(session, bu_dataset, page=1, page_size=1, search=None, decoy=False)
        run_id = _first_run(int(dataset["dataset_id"]))
        if matches.items:
            match = require_bu_match(session, int(dataset["dataset_id"]), int(matches.items[0].id))
            ms2 = spectrum_facade.get_match_ms2(session, bu_dataset, match)
            ms1 = spectrum_facade.get_match_ms1(session, bu_dataset, match)
            xic = xic_service.get_match_xic(session, bu_dataset, match, ppm=10.0)
        else:
            ms2 = ms1 = xic = None
        chrom = (
            chromatogram_service.get_chromatogram(session, bu_dataset, run_id, chrom_type="tic")
            if run_id is not None
            else None
        )
        return {
            "overview_matches": overview.counts.matches,
            "match_list_total": matches.total,
            "protein_list_total": proteins.total,
            "ms2_points": len(ms2.mz) if ms2 is not None else 0,
            "ms1_points": len(ms1.mz) if ms1 is not None else 0,
            "xic_points": len(xic.rt) if xic is not None else 0,
            "chrom_points": len(chrom.rt) if chrom is not None else 0,
        }


def _verify_spectra(dataset: dict[str, Any]) -> dict[str, Any]:
    from app.services.mzml_scan_index import load_scan_index
    from app.services.mzml_scan_reader import get_spectrum_by_scan

    dataset_id = int(dataset["dataset_id"])
    run_id = _first_run(dataset_id)
    if run_id is None:
        return {"runs_readable": 0, "scan_count": 0, "sample_points": 0}
    with SessionLocal() as session:
        index = load_scan_index(session, dataset_id, run_id)
        scan_number = int(index.scan_number[0]) if index.scan_count else None
        if scan_number is None:
            return {"runs_readable": 0, "scan_count": int(index.scan_count), "sample_points": 0}
        spectrum, _committed = get_spectrum_by_scan(session, dataset_id, run_id, scan_number)
        return {
            "runs_readable": 1,
            "scan_count": int(index.scan_count),
            "sample_scan": scan_number,
            "sample_points": min(len(spectrum.get("mz") or []), len(spectrum.get("intensity") or [])),
        }


def _first_cutoff(dataset_id: int) -> str | None:
    with SessionLocal() as session:
        value = session.scalar(
            text(
                """
                SELECT jsonb_extract_path_text(extra_metadata, 'source_cutoff')
                FROM identification_matches
                WHERE dataset_id = :dataset_id
                  AND jsonb_extract_path_text(extra_metadata, 'source_cutoff') IS NOT NULL
                ORDER BY 1
                LIMIT 1
                """
            ),
            {"dataset_id": dataset_id},
        )
        return str(value) if value else None


def _verify_top_down(dataset: dict[str, Any]) -> dict[str, Any]:
    from app.api.v1 import proteins as protein_api
    from app.api.v1 import proteoforms as proteoform_api
    from app.api.v1 import prsms as prsm_api

    slug = str(dataset["slug"])
    dataset_id = int(dataset["dataset_id"])
    cutoff = _first_cutoff(dataset_id)
    if cutoff is None:
        spectra = _verify_spectra(dataset)
        return {"cutoff": None, **spectra}
    with SessionLocal() as session:
        proteins = protein_api.list_proteins(
            slug=slug,
            cutoff=cutoff,
            session=session,
            page=1,
            page_size=1,
            search=None,
            sort="sequence_id",
            order="asc",
        )
        proteoforms = proteoform_api.list_proteoforms(
            slug=slug,
            cutoff=cutoff,
            session=session,
            page=1,
            page_size=1,
            protein_id=None,
            sort="proteoform_id",
            order="asc",
        )
        prsms = prsm_api.list_prsms(
            slug=slug,
            cutoff=cutoff,
            session=session,
            page=1,
            page_size=1,
            proteoform_id=None,
            protein_id=None,
            sort="e_value",
            order="asc",
        )
        if prsms.items:
            detail = prsm_api.get_prsm(slug=slug, cutoff=cutoff, prsm_id=int(prsms.items[0].prsm_id), session=session)
            peak_count = len(detail.ms_peaks or [])
        else:
            peak_count = 0
        return {
            "cutoff": cutoff,
            "protein_list_total": proteins.total,
            "proteoform_list_total": proteoforms.total,
            "prsm_list_total": prsms.total,
            "prsm_detail_peaks": peak_count,
        }


def _verify(case: Case, dataset: dict[str, Any]) -> dict[str, Any]:
    if str(dataset.get("status")) != "READY":
        raise RuntimeError(f"dataset status is not READY: {dataset.get('status')}")
    if case.verify_profile == "bottom_up":
        return _verify_bottom_up(dataset)
    if case.verify_profile == "top_down":
        return _verify_top_down(dataset)
    return _verify_spectra(dataset)


def _verify_existing_import(
    *,
    import_type: str,
    verify_profile: str,
    root: Path,
) -> dict[str, Any]:
    started_at = time.perf_counter()
    print(f"\n=== {import_type} (verify-existing) ===", flush=True)
    dataset = _latest_support_dataset(import_type)
    if dataset is None:
        raise RuntimeError(f"no existing support dataset found for {import_type}")
    dataset_id = int(dataset["dataset_id"])
    zp = _active_zp(dataset_id)
    case = Case(
        import_type,
        root / import_type,
        "verify-existing",
        verify_profile,
        0,
    )
    display = _verify(case, dataset)
    return {
        "import_type": import_type,
        "method": "verify-existing",
        "source_dir": str(dataset.get("source_root") or root / import_type),
        "slug": dataset["slug"],
        "job": {"status": "success", "job_id": None, "error": None},
        "dataset": {
            "dataset_id": dataset_id,
            "status": dataset["status"],
            "analysis_mode": dataset["analysis_mode"],
            "source_software": dataset["source_software"],
            "capabilities": dataset["capabilities"],
        },
        "counts": _counts(dataset_id),
        "zp": {
            "active": zp is not None,
            "asset_id": zp.get("asset_id") if zp else None,
            "format_version": zp.get("format_version") if zp else None,
            "path": zp.get("zp_path") if zp else None,
        },
        "display": display,
        "seconds": round(time.perf_counter() - started_at, 3),
    }


def _run_case(case: Case) -> dict[str, Any]:
    slug = _slug(RUN_LABEL, case.import_type)
    started_at = time.perf_counter()
    print(f"\n=== {case.import_type} ({case.method}) ===", flush=True)
    _check_space(f"before {case.import_type}")
    if case.method == "managed-upload":
        job_id = asyncio.run(_upload_tree(case))
    else:
        job_id = _path_import(case)
    job = _wait_job(job_id, timeout_seconds=case.timeout_seconds)
    dataset = _dataset_row(slug)
    if dataset is None:
        raise RuntimeError(f"dataset was not created for slug={slug}")
    dataset_id = int(dataset["dataset_id"])
    zp = _active_zp(dataset_id)
    display = _verify(case, dataset)
    _check_space(f"after {case.import_type}")
    return {
        "import_type": case.import_type,
        "method": case.method,
        "source_dir": str(case.source_dir),
        "slug": slug,
        "job": job,
        "dataset": {
            "dataset_id": dataset_id,
            "status": dataset["status"],
            "analysis_mode": dataset["analysis_mode"],
            "source_software": dataset["source_software"],
            "capabilities": dataset["capabilities"],
        },
        "counts": _counts(dataset_id),
        "zp": {
            "active": zp is not None,
            "asset_id": zp.get("asset_id") if zp else None,
            "format_version": zp.get("format_version") if zp else None,
            "path": zp.get("zp_path") if zp else None,
        },
        "display": display,
        "seconds": round(time.perf_counter() - started_at, 3),
    }


def _run_agent_zp(root: Path) -> dict[str, Any]:
    slug = _slug(RUN_LABEL, "agent_zp")
    zp_path = root / "AGENT_ZP" / "diaclip-active.zp"
    print("\n=== AGENT_ZP (register_existing_zp) ===", flush=True)
    _check_space("before AGENT_ZP")
    started_at = time.perf_counter()
    with SessionLocal() as session:
        result = import_agent_zp_candidate(
            session,
            AgentZpImportCreateIn(
                source_path=str(zp_path),
                slug=slug,
                name="Support Acceptance AGENT_ZP",
                description="Generated by cs/支持格式上传验收.py",
                analysis_category="SPECTRA_ONLY",
                source_profile="support_all_data",
                binary_operation="register_existing_zp",
            ),
        )
        dataset = _dataset_row(result.dataset_slug)
        if dataset is None:
            raise RuntimeError("Agent-ZP dataset was not created")
        display = _verify_spectra(dataset)
        _check_space("after AGENT_ZP")
        return {
            "import_type": "AGENT_ZP",
            "method": "register-existing-zp",
            "source_dir": str(zp_path),
            "slug": result.dataset_slug,
            "job": {"status": result.status, "job_id": None, "error": None},
            "dataset": {
                "dataset_id": result.dataset_id,
                "status": dataset["status"],
                "analysis_mode": dataset["analysis_mode"],
                "source_software": dataset["source_software"],
                "capabilities": dataset["capabilities"],
            },
            "counts": _counts(result.dataset_id),
            "zp": {
                "active": True,
                "asset_id": _active_zp(result.dataset_id).get("asset_id"),
                "format_version": result.zp_format_version,
                "path": str(zp_path),
            },
            "display": display,
            "seconds": round(time.perf_counter() - started_at, 3),
        }


def _write_report(
    root: Path,
    results: list[dict[str, Any]],
    paths: tuple[Path, Path] | None = None,
) -> tuple[Path, Path]:
    if paths is None:
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        json_path = root / f"验收结果-{stamp}.json"
        md_path = root / f"验收结果-{stamp}.md"
    else:
        json_path, md_path = paths
    json_path.write_text(json.dumps(results, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
    lines = [
        "# 支持格式上传验收结果",
        "",
        "| 类型 | 方法 | 导入 | READY | ZP | 展示检查 | 数据集 | 耗时(s) |",
        "|---|---|---:|---:|---:|---|---|---:|",
    ]
    for item in results:
        job_status = item.get("job", {}).get("status")
        dataset = item.get("dataset", {})
        display_ok = "OK" if item.get("display") else "FAIL"
        lines.append(
            "| {import_type} | {method} | {job_status} | {ready} | {zp} | {display_ok} | {slug} | {seconds} |".format(
                import_type=item.get("import_type"),
                method=item.get("method"),
                job_status=job_status,
                ready=dataset.get("status") == "READY",
                zp=item.get("zp", {}).get("active"),
                display_ok=display_ok,
                slug=item.get("slug"),
                seconds=item.get("seconds"),
            )
        )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return json_path, md_path


def _bootstrap() -> None:
    import_jobs.ensure_jobs_table()
    import_jobs.ensure_dataset_fingerprint_schema()
    import_jobs.ensure_runs_metadata_schema()
    if settings.zp_management_enabled:
        ensure_zp_conversion_schema()


def main() -> int:
    parser = argparse.ArgumentParser(description="Run support-format upload acceptance checks.")
    parser.add_argument("--root", default=str(settings.resolved_data_root / "支持所有数据"))
    parser.add_argument("--only", nargs="*", help="Optional import types to run.")
    parser.add_argument(
        "--verify-existing",
        action="store_true",
        help="Verify the newest existing support datasets instead of importing again.",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    selected = {item.upper() for item in args.only or []}
    _bootstrap()
    cases = [case for case in _all_cases(root) if not selected or case.import_type in selected]
    results: list[dict[str, Any]] = []
    report_paths = _write_report(root, results)
    abort_remaining = False
    for case in cases:
        try:
            results.append(
                _verify_existing_import(
                    import_type=case.import_type,
                    verify_profile=case.verify_profile,
                    root=root,
                )
                if args.verify_existing
                else _run_case(case)
            )
        except (UploadError, AgentZpError, Exception) as exc:  # noqa: BLE001
            results.append(
                {
                    "import_type": case.import_type,
                    "method": case.method,
                    "source_dir": str(case.source_dir),
                    "slug": _slug(RUN_LABEL, case.import_type),
                    "job": {"status": "failed", "job_id": None, "error": str(exc)},
                    "dataset": None,
                    "counts": {},
                    "zp": {"active": False},
                    "display": {},
                    "seconds": None,
                }
            )
            if "LOW_SPACE" in str(exc):
                _write_report(root, results, report_paths)
                abort_remaining = True
                break
        _write_report(root, results, report_paths)
    if not abort_remaining and (not selected or "AGENT_ZP" in selected):
        try:
            results.append(
                _verify_existing_import(
                    import_type="AGENT_ZP",
                    verify_profile="spectra",
                    root=root,
                )
                if args.verify_existing
                else _run_agent_zp(root)
            )
        except (AgentZpError, Exception) as exc:  # noqa: BLE001
            results.append(
                {
                    "import_type": "AGENT_ZP",
                    "method": "register-existing-zp",
                    "source_dir": str(root / "AGENT_ZP" / "diaclip-active.zp"),
                    "slug": _slug(RUN_LABEL, "agent_zp"),
                    "job": {"status": "failed", "job_id": None, "error": str(exc)},
                    "dataset": None,
                    "counts": {},
                    "zp": {"active": False},
                    "display": {},
                    "seconds": None,
                }
            )
        _write_report(root, results, report_paths)
    json_path, md_path = _write_report(root, results, report_paths)
    print(f"\n[report] {json_path}", flush=True)
    print(f"[report] {md_path}", flush=True)
    print(json.dumps(results, ensure_ascii=False, indent=2, default=str), flush=True)
    return 0 if all(item.get("job", {}).get("status") == "success" for item in results) else 1


RUN_LABEL = datetime.now().strftime("%Y%m%d%H%M%S")


if __name__ == "__main__":
    raise SystemExit(main())
