export const CHART_COLORS = {
  grid: "hsl(var(--chart-grid))",
  axis: "hsl(var(--chart-axis))",
  text: "hsl(var(--chart-text))",
  unmatched: "hsl(var(--chart-unmatched))",
  selection: "hsl(var(--chart-selection))",
  selectionSoft: "hsl(var(--chart-selection-soft))",
  selectionForeground: "hsl(var(--chart-selection-foreground))",
  series: [
    "hsl(var(--chart-series-1))",
    "hsl(var(--chart-series-2))",
    "hsl(var(--chart-series-3))",
    "hsl(var(--chart-series-4))",
    "hsl(var(--chart-series-5))",
    "hsl(var(--chart-series-6))",
    "hsl(var(--chart-series-7))",
    "hsl(var(--chart-series-8))",
    "hsl(var(--chart-series-9))",
    "hsl(var(--chart-series-10))",
    "hsl(var(--chart-series-11))",
    "hsl(var(--chart-series-12))",
  ],
  heat: [
    "hsl(var(--chart-heat-1))",
    "hsl(var(--chart-heat-2))",
    "hsl(var(--chart-heat-3))",
    "hsl(var(--chart-heat-4))",
    "hsl(var(--chart-heat-5))",
    "hsl(var(--chart-heat-6))",
  ],
} as const;
