"""fix proteoform unique

Revision ID: 4f2fa3d9ae4f
Revises: 9e67d080f5fb
Create Date: 2026-04-23 17:51:12.768697

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f2fa3d9ae4f'
down_revision: Union[str, None] = '9e67d080f5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_proteoform_cutoff_id'), 'proteoforms', type_='unique')
    op.create_index('ix_proteoform_cutoff_seq', 'proteoforms', ['cutoff_id', 'sequence_id', 'proteoform_id'], unique=False)
    op.create_unique_constraint('uq_proteoform_protein_id', 'proteoforms', ['cutoff_id', 'protein_id', 'proteoform_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_proteoform_protein_id', 'proteoforms', type_='unique')
    op.drop_index('ix_proteoform_cutoff_seq', table_name='proteoforms')
    op.create_unique_constraint(op.f('uq_proteoform_cutoff_id'), 'proteoforms', ['cutoff_id', 'proteoform_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
