"""initial schema

Revision ID: 9e67d080f5fb
Revises: 
Create Date: 2026-04-23 17:49:49.000133

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9e67d080f5fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_slug'), 'datasets', ['slug'], unique=True)
    op.create_table('cutoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('data_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'kind', name='uq_cutoff_dataset_kind')
    )
    op.create_index(op.f('ix_cutoffs_dataset_id'), 'cutoffs', ['dataset_id'], unique=False)
    op.create_table('proteins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutoff_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('sequence_name', sa.String(length=255), nullable=False),
    sa.Column('sequence_description', sa.Text(), nullable=True),
    sa.Column('compatible_proteoform_number', sa.Integer(), nullable=False),
    sa.Column('prsm_number', sa.Integer(), nullable=False),
    sa.Column('best_prsm_id', sa.Integer(), nullable=True),
    sa.Column('best_prsm_e_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cutoff_id'], ['cutoffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cutoff_id', 'sequence_id', name='uq_protein_cutoff_seq')
    )
    op.create_index('ix_protein_cutoff_name', 'proteins', ['cutoff_id', 'sequence_name'], unique=False)
    op.create_index(op.f('ix_proteins_cutoff_id'), 'proteins', ['cutoff_id'], unique=False)
    op.create_table('proteoforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutoff_id', sa.Integer(), nullable=False),
    sa.Column('protein_id', sa.Integer(), nullable=False),
    sa.Column('proteoform_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('sequence_name', sa.String(length=255), nullable=False),
    sa.Column('proteoform_mass', sa.Float(), nullable=True),
    sa.Column('prsm_number', sa.Integer(), nullable=False),
    sa.Column('best_prsm_id', sa.Integer(), nullable=True),
    sa.Column('best_prsm_e_value', sa.Float(), nullable=True),
    sa.Column('n_acetylation', sa.Integer(), nullable=True),
    sa.Column('unexpected_shift_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cutoff_id'], ['cutoffs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protein_id'], ['proteins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cutoff_id', 'proteoform_id', name='uq_proteoform_cutoff_id')
    )
    op.create_index('ix_proteoform_protein', 'proteoforms', ['protein_id'], unique=False)
    op.create_index(op.f('ix_proteoforms_cutoff_id'), 'proteoforms', ['cutoff_id'], unique=False)
    op.create_table('prsms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutoff_id', sa.Integer(), nullable=False),
    sa.Column('proteoform_id', sa.Integer(), nullable=False),
    sa.Column('prsm_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('e_value', sa.Float(), nullable=True),
    sa.Column('fdr', sa.Float(), nullable=True),
    sa.Column('matched_fragment_number', sa.Integer(), nullable=True),
    sa.Column('matched_peak_number', sa.Integer(), nullable=True),
    sa.Column('spectrum_file_name', sa.Text(), nullable=True),
    sa.Column('ms1_scans', sa.Text(), nullable=True),
    sa.Column('ms2_scans', sa.Text(), nullable=True),
    sa.Column('ms1_ids', sa.Text(), nullable=True),
    sa.Column('ms2_ids', sa.Text(), nullable=True),
    sa.Column('precursor_mono_mass', sa.Float(), nullable=True),
    sa.Column('precursor_charge', sa.Integer(), nullable=True),
    sa.Column('precursor_mz', sa.Float(), nullable=True),
    sa.Column('feature_inte', sa.Float(), nullable=True),
    sa.Column('proteoform_mass', sa.Float(), nullable=True),
    sa.Column('annotated_protein', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ms_header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ms_peaks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cutoff_id'], ['cutoffs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proteoform_id'], ['proteoforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cutoff_id', 'prsm_id', name='uq_prsm_cutoff_id')
    )
    op.create_index('ix_prsm_evalue', 'prsms', ['cutoff_id', 'e_value'], unique=False)
    op.create_index('ix_prsm_proteoform', 'prsms', ['proteoform_id'], unique=False)
    op.create_index(op.f('ix_prsms_cutoff_id'), 'prsms', ['cutoff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prsms_cutoff_id'), table_name='prsms')
    op.drop_index('ix_prsm_proteoform', table_name='prsms')
    op.drop_index('ix_prsm_evalue', table_name='prsms')
    op.drop_table('prsms')
    op.drop_index(op.f('ix_proteoforms_cutoff_id'), table_name='proteoforms')
    op.drop_index('ix_proteoform_protein', table_name='proteoforms')
    op.drop_table('proteoforms')
    op.drop_index(op.f('ix_proteins_cutoff_id'), table_name='proteins')
    op.drop_index('ix_protein_cutoff_name', table_name='proteins')
    op.drop_table('proteins')
    op.drop_index(op.f('ix_cutoffs_dataset_id'), table_name='cutoffs')
    op.drop_table('cutoffs')
    op.drop_index(op.f('ix_datasets_slug'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
